name: warps
version: '${version}'
main: org.pantouflemc.warps.Warps
api-version: '1.20'
description: A simple warps plugin
website: http://pantouflemc.org
authors: [PantoufleMC, Doriantrn]

commands:
  warps.create:
    description: Create a warp
    usage: /<command> <name>
    aliases: [createwarp]
  warps.delete:
    description: Delete a warp
    usage: /<command> <name>
    aliases: [deletewarp]
  warps.list:
    description: List all warps
    usage: /<command>
    aliases: [listwarps]
  warps.teleport:
    description: Teleport to a warp
    usage: /<command> <name>
    aliases: [warp]
